"""initial schema

Revision ID: 4fb86814b892
Revises: 
Create Date: 2026-09-09 21:50:07.220234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fb86814b892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('tree_pollen', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('grass_pollen', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('weed_pollen', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('environment_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_snapshot_id'], ['environment_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('hospital_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_searches_user_id'), 'hospital_searches', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_pollen', sa.Boolean(), nullable=False),
    sa.Column('alert_air_quality', sa.Boolean(), nullable=False),
    sa.Column('alert_weather', sa.Boolean(), nullable=False),
    sa.Column('min_risk_level', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('user_allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_allergies_user_id'), 'user_allergies', ['user_id'], unique=False)
    op.create_table('hospital_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_search_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_search_id'], ['hospital_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_results_hospital_search_id'), 'hospital_results', ['hospital_search_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('symptom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('possible_trigger', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('breathing_difficulty', sa.Boolean(), nullable=False),
    sa.Column('airway_swelling', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_events_user_id'), 'symptom_events', ['user_id'], unique=False)
    op.create_table('triage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_event_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symptom_event_id'], ['symptom_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_results_symptom_event_id'), 'triage_results', ['symptom_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_results_symptom_event_id'), table_name='triage_results')
    op.drop_table('triage_results')
    op.drop_index(op.f('ix_symptom_events_user_id'), table_name='symptom_events')
    op.drop_table('symptom_events')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hospital_results_hospital_search_id'), table_name='hospital_results')
    op.drop_table('hospital_results')
    op.drop_index(op.f('ix_user_allergies_user_id'), table_name='user_allergies')
    op.drop_table('user_allergies')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_hospital_searches_user_id'), table_name='hospital_searches')
    op.drop_table('hospital_searches')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('environment_snapshots')
    # ### end Alembic commands ###
